package com.tabao.bussiness.model;

import com.tabao.core.base.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class SysDic extends BaseModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.dic_code
     *
     * @mbggenerated
     */
    private String dicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.dic_name
     *
     * @mbggenerated
     */
    private String dicName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.cre_user
     *
     * @mbggenerated
     */
    private String creUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.cre_time
     *
     * @mbggenerated
     */
    private Date creTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.mod_user
     *
     * @mbggenerated
     */
    private String modUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.mod_time
     *
     * @mbggenerated
     */
    private Date modTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_dic.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_dic
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.dic_code
     *
     * @return the value of sys_dic.dic_code
     *
     * @mbggenerated
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.dic_code
     *
     * @param dicCode the value for sys_dic.dic_code
     *
     * @mbggenerated
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode == null ? null : dicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.dic_name
     *
     * @return the value of sys_dic.dic_name
     *
     * @mbggenerated
     */
    public String getDicName() {
        return dicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.dic_name
     *
     * @param dicName the value for sys_dic.dic_name
     *
     * @mbggenerated
     */
    public void setDicName(String dicName) {
        this.dicName = dicName == null ? null : dicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.remark
     *
     * @return the value of sys_dic.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.remark
     *
     * @param remark the value for sys_dic.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.cre_user
     *
     * @return the value of sys_dic.cre_user
     *
     * @mbggenerated
     */
    public String getCreUser() {
        return creUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.cre_user
     *
     * @param creUser the value for sys_dic.cre_user
     *
     * @mbggenerated
     */
    public void setCreUser(String creUser) {
        this.creUser = creUser == null ? null : creUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.cre_time
     *
     * @return the value of sys_dic.cre_time
     *
     * @mbggenerated
     */
    public Date getCreTime() {
        return creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.cre_time
     *
     * @param creTime the value for sys_dic.cre_time
     *
     * @mbggenerated
     */
    public void setCreTime(Date creTime) {
        this.creTime = creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.mod_user
     *
     * @return the value of sys_dic.mod_user
     *
     * @mbggenerated
     */
    public String getModUser() {
        return modUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.mod_user
     *
     * @param modUser the value for sys_dic.mod_user
     *
     * @mbggenerated
     */
    public void setModUser(String modUser) {
        this.modUser = modUser == null ? null : modUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.mod_time
     *
     * @return the value of sys_dic.mod_time
     *
     * @mbggenerated
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.mod_time
     *
     * @param modTime the value for sys_dic.mod_time
     *
     * @mbggenerated
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_dic.is_deleted
     *
     * @return the value of sys_dic.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_dic.is_deleted
     *
     * @param isDeleted the value for sys_dic.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dic
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dicCode=").append(dicCode);
        sb.append(", dicName=").append(dicName);
        sb.append(", remark=").append(remark);
        sb.append(", creUser=").append(creUser);
        sb.append(", creTime=").append(creTime);
        sb.append(", modUser=").append(modUser);
        sb.append(", modTime=").append(modTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}