package com.tabao.bussiness.model;

import com.tabao.core.base.model.BaseModel;
import java.io.Serializable;
import java.util.Date;

public class SysEntry extends BaseModel implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.dic_code
     *
     * @mbggenerated
     */
    private String dicCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.entry_code
     *
     * @mbggenerated
     */
    private String entryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.entry_name
     *
     * @mbggenerated
     */
    private String entryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.entry_value
     *
     * @mbggenerated
     */
    private String entryValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.cre_user
     *
     * @mbggenerated
     */
    private String creUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.cre_time
     *
     * @mbggenerated
     */
    private Date creTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.mod_user
     *
     * @mbggenerated
     */
    private String modUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.mod_time
     *
     * @mbggenerated
     */
    private Date modTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_entry.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_entry
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.dic_code
     *
     * @return the value of sys_entry.dic_code
     *
     * @mbggenerated
     */
    public String getDicCode() {
        return dicCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.dic_code
     *
     * @param dicCode the value for sys_entry.dic_code
     *
     * @mbggenerated
     */
    public void setDicCode(String dicCode) {
        this.dicCode = dicCode == null ? null : dicCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.entry_code
     *
     * @return the value of sys_entry.entry_code
     *
     * @mbggenerated
     */
    public String getEntryCode() {
        return entryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.entry_code
     *
     * @param entryCode the value for sys_entry.entry_code
     *
     * @mbggenerated
     */
    public void setEntryCode(String entryCode) {
        this.entryCode = entryCode == null ? null : entryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.entry_name
     *
     * @return the value of sys_entry.entry_name
     *
     * @mbggenerated
     */
    public String getEntryName() {
        return entryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.entry_name
     *
     * @param entryName the value for sys_entry.entry_name
     *
     * @mbggenerated
     */
    public void setEntryName(String entryName) {
        this.entryName = entryName == null ? null : entryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.entry_value
     *
     * @return the value of sys_entry.entry_value
     *
     * @mbggenerated
     */
    public String getEntryValue() {
        return entryValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.entry_value
     *
     * @param entryValue the value for sys_entry.entry_value
     *
     * @mbggenerated
     */
    public void setEntryValue(String entryValue) {
        this.entryValue = entryValue == null ? null : entryValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.remark
     *
     * @return the value of sys_entry.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.remark
     *
     * @param remark the value for sys_entry.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.cre_user
     *
     * @return the value of sys_entry.cre_user
     *
     * @mbggenerated
     */
    public String getCreUser() {
        return creUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.cre_user
     *
     * @param creUser the value for sys_entry.cre_user
     *
     * @mbggenerated
     */
    public void setCreUser(String creUser) {
        this.creUser = creUser == null ? null : creUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.cre_time
     *
     * @return the value of sys_entry.cre_time
     *
     * @mbggenerated
     */
    public Date getCreTime() {
        return creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.cre_time
     *
     * @param creTime the value for sys_entry.cre_time
     *
     * @mbggenerated
     */
    public void setCreTime(Date creTime) {
        this.creTime = creTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.mod_user
     *
     * @return the value of sys_entry.mod_user
     *
     * @mbggenerated
     */
    public String getModUser() {
        return modUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.mod_user
     *
     * @param modUser the value for sys_entry.mod_user
     *
     * @mbggenerated
     */
    public void setModUser(String modUser) {
        this.modUser = modUser == null ? null : modUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.mod_time
     *
     * @return the value of sys_entry.mod_time
     *
     * @mbggenerated
     */
    public Date getModTime() {
        return modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.mod_time
     *
     * @param modTime the value for sys_entry.mod_time
     *
     * @mbggenerated
     */
    public void setModTime(Date modTime) {
        this.modTime = modTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_entry.is_deleted
     *
     * @return the value of sys_entry.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_entry.is_deleted
     *
     * @param isDeleted the value for sys_entry.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_entry
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dicCode=").append(dicCode);
        sb.append(", entryCode=").append(entryCode);
        sb.append(", entryName=").append(entryName);
        sb.append(", entryValue=").append(entryValue);
        sb.append(", remark=").append(remark);
        sb.append(", creUser=").append(creUser);
        sb.append(", creTime=").append(creTime);
        sb.append(", modUser=").append(modUser);
        sb.append(", modTime=").append(modTime);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}